pr

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -10,16 +10,16 @@ jobs:
     name: docker_image
     runs-on: ubuntu-latest
     steps:
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.8.15'
+      # - name: Setup Python
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: '3.8.15'
 
-      - name: check for deploy
-        if: contains(github.event.head_commit.message, 'deploy')
-        run: |
-          DEPLOY=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*\[deploy:[[:space:]]*\([^]]*\)].*/\1/p')
-          echo "DEPLOY=$DEPLOY" >> $GITHUB_ENV
+      # - name: check for deploy
+      #   if: contains(github.event.head_commit.message, 'deploy')
+      #   run: |
+      #     DEPLOY=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*\[deploy:[[:space:]]*\([^]]*\)].*/\1/p')
+      #     echo "DEPLOY=$DEPLOY" >> $GITHUB_ENV
 
       - name: checkout code
         uses: actions/checkout@v4
@@ -68,50 +68,49 @@ jobs:
         run: |
            git checkout -B ${{ env.CURRENT_DATE }}-auto-deploy
            git add .
-           git push origin ${{ env.CURRENT_DATE }}-auto-deploy
-          #  # get base branch name (usually master or main) through git command
-          #  BASE=$(git remote show origin | grep HEAD | awk '{print $3}')
-          #  echo "BASE=$BASE"
+           # get base branch name (usually master or main) through git command
+           BASE=$(git remote show origin | grep HEAD | awk '{print $3}')
+           echo "BASE=$BASE"
 
-          #  postData='{
-          #    "title":"this is title",
-          #    "body":"this is body",
-          #    "head":"${{ env.CURRENT_DATE }}-auto-deploy",
-          #    "base":"'$BASE'"
-          #  }'
+           postData='{
+             "title":"this is title",
+             "body":"this is body",
+             "head":"${{ env.CURRENT_DATE }}-auto-deploy",
+             "base":"main"
+           }'
    
-          #  # use curl -w and jq -s to save response and status_code header as one json object
-          #  response=$( curl -L \
-          #  -X POST \
-          #  -H "Accept: application/vnd.github+json" \
-          #  -H "Authorization: Bearer ${{ secrets.MY_GITHUB_ACTION_TOKEN }}" \
-          #  -H "X-GitHub-Api-Version: 2022-11-28" \
-          #  https://api.github.com/repos/${{ github.repository }}/pulls \
-          #  -d "${postData}" \
-          #  -w '{"status_code": "%{http_code}"}' | jq -s )
+           # use curl -w and jq -s to save response and status_code header as one json object
+           response=$( curl -L \
+           -X POST \
+           -H "Accept: application/vnd.github+json" \
+           -H "Authorization: Bearer ${{ secrets.MY_GITHUB_ACTION_TOKEN }}" \
+           -H "X-GitHub-Api-Version: 2022-11-28" \
+           https://api.github.com/repos/${{ github.repository }}/pulls \
+           -d "${postData}" \
+           -w '{"status_code": "%{http_code}"}' | jq -s )
     
-          #  echo -e "Response body is:\n$response"
+           echo -e "Response body is:\n$response"
    
-          #  status_code=$(echo $response | jq -r '.[1].status_code')
+           status_code=$(echo $response | jq -r '.[1].status_code')
    
-          #  if [ $status_code == '422' ]
-          #  then
-          #    # get reason for PR not being created.
-          #    # (Two jq commands since errors is an array holding json)
-          #    reason=$(echo $response | jq -r '.[0].errors' | jq -r '.[0].message')
-          #    echo "$reason"
-          #    if [[ $reason =~ 'pull request already exists' ]]
-          #    then
-          #       echo "Workflow will not recreate or replace the pull request"
-          #    else
-          #       exit 1
-          #    fi
-          #  elif [ $status_code == '201' ]
-          #  then
-          #    # save pull request url for notification step
-          #    PR_URL=$(echo $response | jq -r ".[0].html_url")
-          #    echo "pullreq_url=$PR_URL" >> $GITHUB_OUTPUT
-          #  else
-          #    echo "Unexpected status code $status_code in create PR API call. Exiting."
-          #    exit 1
-          #  fi
+           if [ $status_code == '422' ]
+           then
+             # get reason for PR not being created.
+             # (Two jq commands since errors is an array holding json)
+             reason=$(echo $response | jq -r '.[0].errors' | jq -r '.[0].message')
+             echo "$reason"
+             if [[ $reason =~ 'pull request already exists' ]]
+             then
+                echo "Workflow will not recreate or replace the pull request"
+             else
+                exit 1
+             fi
+           elif [ $status_code == '201' ]
+           then
+             # save pull request url for notification step
+             PR_URL=$(echo $response | jq -r ".[0].html_url")
+             echo "pullreq_url=$PR_URL" >> $GITHUB_OUTPUT
+           else
+             echo "Unexpected status code $status_code in create PR API call. Exiting."
+             exit 1
+           fi
